<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class PatientSeeder extends Seeder
{
    public function run(): void
    {
        $patients = [
            ['nom' => 'Diallo', 'prenom' => 'Mariam', 'genre' => 'M', 'age' => 8, 'telephone' => '78423964', 'groupe_sanguin' => 'O+', 'adresse' => "Lafiabougou, Bamako"],
            ['nom' => 'Maiga', 'prenom' => 'Oumar', 'genre' => 'M', 'age' => 4, 'telephone' => '78476707', 'groupe_sanguin' => 'O-', 'adresse' => "Banankabougou, Bamako"],
            ['nom' => 'Keita', 'prenom' => 'Ibrahim', 'genre' => 'M', 'age' => 68, 'telephone' => '71418239', 'groupe_sanguin' => 'AB+', 'adresse' => "Banankabougou, Bamako"],
            ['nom' => 'Dembele', 'prenom' => 'Hawa', 'genre' => 'F', 'age' => 30, 'telephone' => '78970607', 'groupe_sanguin' => 'B+', 'adresse' => "Kalaban Coura, Bamako"],
            ['nom' => 'Cisse', 'prenom' => 'Salimata', 'genre' => 'F', 'age' => 46, 'telephone' => '77647495', 'groupe_sanguin' => 'O-', 'adresse' => "Badalabougou, Bamako"],
            ['nom' => 'Toure', 'prenom' => 'Fatoumata', 'genre' => 'F', 'age' => 17, 'telephone' => '74715888', 'groupe_sanguin' => 'A+', 'adresse' => "Sabalibougou, Bamako"],
            ['nom' => 'Sidibe', 'prenom' => 'Moussa', 'genre' => 'F', 'age' => 76, 'telephone' => '74187205', 'groupe_sanguin' => 'A+', 'adresse' => "Missabougou, Bamako"],
            ['nom' => 'Camara', 'prenom' => 'Ibrahim', 'genre' => 'F', 'age' => 29, 'telephone' => '77566175', 'groupe_sanguin' => 'O-', 'adresse' => "Banankabougou, Bamako"],
            ['nom' => 'Barry', 'prenom' => 'Bakary', 'genre' => 'F', 'age' => 18, 'telephone' => '78862186', 'groupe_sanguin' => 'AB+', 'adresse' => "Missabougou, Bamako"],
            ['nom' => 'Konate', 'prenom' => 'Mariam', 'genre' => 'M', 'age' => 76, 'telephone' => '75874328', 'groupe_sanguin' => 'O+', 'adresse' => "Magnambougou, Bamako"],
            ['nom' => 'Sangare', 'prenom' => 'Salimata', 'genre' => 'F', 'age' => 17, 'telephone' => '74351726', 'groupe_sanguin' => 'O+', 'adresse' => "Hamdallaye, Bamako"],
            ['nom' => 'Sangare', 'prenom' => 'Mariam', 'genre' => 'M', 'age' => 28, 'telephone' => '77490592', 'groupe_sanguin' => 'B+', 'adresse' => "Yirimadio, Bamako"],
            ['nom' => 'Sidibe', 'prenom' => 'Abdoulaye', 'genre' => 'M', 'age' => 39, 'telephone' => '74583559', 'groupe_sanguin' => 'O-', 'adresse' => "Missabougou, Bamako"],
            ['nom' => 'Traore', 'prenom' => 'Seydou', 'genre' => 'M', 'age' => 17, 'telephone' => '71172162', 'groupe_sanguin' => 'AB-', 'adresse' => "Missabougou, Bamako"],
            ['nom' => 'Dembele', 'prenom' => 'Abdoulaye', 'genre' => 'M', 'age' => 47, 'telephone' => '78287698', 'groupe_sanguin' => 'B+', 'adresse' => "Magnambougou, Bamako"],
            ['nom' => 'Traore', 'prenom' => 'Issa', 'genre' => 'F', 'age' => 37, 'telephone' => '78179578', 'groupe_sanguin' => 'A+', 'adresse' => "Magnambougou, Bamako"],
            ['nom' => 'Coulibaly', 'prenom' => 'Seydou', 'genre' => 'M', 'age' => 66, 'telephone' => '76983196', 'groupe_sanguin' => 'A-', 'adresse' => "Missabougou, Bamako"],
            ['nom' => 'Camara', 'prenom' => 'Oumar', 'genre' => 'F', 'age' => 33, 'telephone' => '73407958', 'groupe_sanguin' => 'B+', 'adresse' => "Niamakoro, Bamako"],
            ['nom' => 'Keita', 'prenom' => 'Mariam', 'genre' => 'F', 'age' => 14, 'telephone' => '75596209', 'groupe_sanguin' => 'AB+', 'adresse' => "ACI 2000, Bamako"],
            ['nom' => 'Coulibaly', 'prenom' => 'Fatoumata', 'genre' => 'M', 'age' => 27, 'telephone' => '74541843', 'groupe_sanguin' => 'AB+', 'adresse' => "Badalabougou, Bamako"],
            ['nom' => 'Sissoko', 'prenom' => 'Ibrahim', 'genre' => 'M', 'age' => 43, 'telephone' => '74860274', 'groupe_sanguin' => 'A+', 'adresse' => "ACI 2000, Bamako"],
            ['nom' => 'Dembele', 'prenom' => 'Issa', 'genre' => 'M', 'age' => 50, 'telephone' => '79295565', 'groupe_sanguin' => 'B+', 'adresse' => "Sogoniko, Bamako"],
            ['nom' => 'Sangare', 'prenom' => 'Abdoulaye', 'genre' => 'M', 'age' => 44, 'telephone' => '74926857', 'groupe_sanguin' => 'B-', 'adresse' => "Niamakoro, Bamako"],
            ['nom' => 'Cisse', 'prenom' => 'Fatoumata', 'genre' => 'F', 'age' => 4, 'telephone' => '78177143', 'groupe_sanguin' => 'O+', 'adresse' => "Banankabougou, Bamako"],
            ['nom' => 'Konate', 'prenom' => 'Moussa', 'genre' => 'F', 'age' => 43, 'telephone' => '73246094', 'groupe_sanguin' => 'AB+', 'adresse' => "Banankabougou, Bamako"],
            ['nom' => 'Diarra', 'prenom' => 'Kadidia', 'genre' => 'M', 'age' => 61, 'telephone' => '79234194', 'groupe_sanguin' => 'A-', 'adresse' => "Sabalibougou, Bamako"],
            ['nom' => 'Traore', 'prenom' => 'Aissata', 'genre' => 'F', 'age' => 73, 'telephone' => '74543973', 'groupe_sanguin' => 'B+', 'adresse' => "ACI 2000, Bamako"],
            ['nom' => 'Sissoko', 'prenom' => 'Aissata', 'genre' => 'M', 'age' => 81, 'telephone' => '76979246', 'groupe_sanguin' => 'O+', 'adresse' => "Sabalibougou, Bamako"],
            ['nom' => 'Sidibe', 'prenom' => 'Aissata', 'genre' => 'M', 'age' => 2, 'telephone' => '77471852', 'groupe_sanguin' => 'AB+', 'adresse' => "Missabougou, Bamako"],
            ['nom' => 'Coulibaly', 'prenom' => 'Fatoumata', 'genre' => 'F', 'age' => 88, 'telephone' => '73727239', 'groupe_sanguin' => 'B+', 'adresse' => "Yirimadio, Bamako"],
            ['nom' => 'Toure', 'prenom' => 'Issa', 'genre' => 'M', 'age' => 59, 'telephone' => '73381934', 'groupe_sanguin' => 'B+', 'adresse' => "ACI 2000, Bamako"],
            ['nom' => 'Camara', 'prenom' => 'Ibrahim', 'genre' => 'F', 'age' => 43, 'telephone' => '73999201', 'groupe_sanguin' => 'B-', 'adresse' => "Niamakoro, Bamako"],
            ['nom' => 'Barry', 'prenom' => 'Aissata', 'genre' => 'M', 'age' => 64, 'telephone' => '78661148', 'groupe_sanguin' => 'O+', 'adresse' => "Hamdallaye, Bamako"],
            ['nom' => 'Toure', 'prenom' => 'Seydou', 'genre' => 'F', 'age' => 63, 'telephone' => '77752777', 'groupe_sanguin' => 'B+', 'adresse' => "Niamakoro, Bamako"],
            ['nom' => 'Traore', 'prenom' => 'Oumar', 'genre' => 'F', 'age' => 31, 'telephone' => '78894266', 'groupe_sanguin' => 'AB+', 'adresse' => "Yirimadio, Bamako"],
            ['nom' => 'Cisse', 'prenom' => 'Salimata', 'genre' => 'M', 'age' => 11, 'telephone' => '74208935', 'groupe_sanguin' => 'O-', 'adresse' => "Niamakoro, Bamako"],
            ['nom' => 'Konate', 'prenom' => 'Fatoumata', 'genre' => 'M', 'age' => 72, 'telephone' => '73334658', 'groupe_sanguin' => 'O+', 'adresse' => "Sabalibougou, Bamako"],
            ['nom' => 'Barry', 'prenom' => 'Youssouf', 'genre' => 'F', 'age' => 41, 'telephone' => '72668029', 'groupe_sanguin' => 'O+', 'adresse' => "Badalabougou, Bamako"],
            ['nom' => 'Coulibaly', 'prenom' => 'Mariam', 'genre' => 'M', 'age' => 79, 'telephone' => '75248137', 'groupe_sanguin' => 'AB+', 'adresse' => "Yirimadio, Bamako"],
            ['nom' => 'Diarra', 'prenom' => 'Issa', 'genre' => 'M', 'age' => 16, 'telephone' => '76328441', 'groupe_sanguin' => 'O-', 'adresse' => "Magnambougou, Bamako"],
            ['nom' => 'Diallo', 'prenom' => 'Oumar', 'genre' => 'F', 'age' => 33, 'telephone' => '71968029', 'groupe_sanguin' => 'AB-', 'adresse' => "Kalaban Coura, Bamako"],
            ['nom' => 'Coulibaly', 'prenom' => 'Mariam', 'genre' => 'M', 'age' => 24, 'telephone' => '71967963', 'groupe_sanguin' => 'O+', 'adresse' => "Sogoniko, Bamako"],
            ['nom' => 'Konate', 'prenom' => 'Ibrahim', 'genre' => 'F', 'age' => 76, 'telephone' => '79674233', 'groupe_sanguin' => 'A+', 'adresse' => "Yirimadio, Bamako"],
            ['nom' => 'Traore', 'prenom' => 'Aissata', 'genre' => 'F', 'age' => 74, 'telephone' => '76049426', 'groupe_sanguin' => 'A-', 'adresse' => "Yirimadio, Bamako"],
            ['nom' => 'Sidibe', 'prenom' => 'Oumar', 'genre' => 'M', 'age' => 72, 'telephone' => '73701176', 'groupe_sanguin' => 'B-', 'adresse' => "Magnambougou, Bamako"],
            ['nom' => 'Konate', 'prenom' => 'Oumar', 'genre' => 'M', 'age' => 2, 'telephone' => '77106400', 'groupe_sanguin' => 'B-', 'adresse' => "Lafiabougou, Bamako"],
            ['nom' => 'Sidibe', 'prenom' => 'Aminata', 'genre' => 'F', 'age' => 80, 'telephone' => '76475329', 'groupe_sanguin' => 'AB-', 'adresse' => "Yirimadio, Bamako"],
            ['nom' => 'Sidibe', 'prenom' => 'Ibrahim', 'genre' => 'M', 'age' => 70, 'telephone' => '74251516', 'groupe_sanguin' => 'O+', 'adresse' => "Lafiabougou, Bamako"],
            ['nom' => 'Sidibe', 'prenom' => 'Ibrahim', 'genre' => 'M', 'age' => 61, 'telephone' => '74027882', 'groupe_sanguin' => 'B-', 'adresse' => "Yirimadio, Bamako"],
            ['nom' => 'Barry', 'prenom' => 'Salimata', 'genre' => 'M', 'age' => 50, 'telephone' => '76937512', 'groupe_sanguin' => 'AB+', 'adresse' => "ACI 2000, Bamako"],
            ['nom' => 'Diallo', 'prenom' => 'Bakary', 'genre' => 'M', 'age' => 64, 'telephone' => '71592970', 'groupe_sanguin' => 'A+', 'adresse' => "Hamdallaye, Bamako"],
            ['nom' => 'Keita', 'prenom' => 'Oumar', 'genre' => 'M', 'age' => 58, 'telephone' => '76990858', 'groupe_sanguin' => 'B+', 'adresse' => "Yirimadio, Bamako"],
            ['nom' => 'Konate', 'prenom' => 'Hawa', 'genre' => 'M', 'age' => 81, 'telephone' => '79727467', 'groupe_sanguin' => 'AB+', 'adresse' => "ACI 2000, Bamako"],
            ['nom' => 'Dembele', 'prenom' => 'Oumar', 'genre' => 'F', 'age' => 60, 'telephone' => '78911113', 'groupe_sanguin' => 'B+', 'adresse' => "Kalaban Coura, Bamako"],
            ['nom' => 'Diallo', 'prenom' => 'Kadidia', 'genre' => 'M', 'age' => 61, 'telephone' => '74378044', 'groupe_sanguin' => 'O+', 'adresse' => "Sabalibougou, Bamako"],
            ['nom' => 'Toure', 'prenom' => 'Bakary', 'genre' => 'M', 'age' => 63, 'telephone' => '74251492', 'groupe_sanguin' => 'AB-', 'adresse' => "Banankabougou, Bamako"],
            ['nom' => 'Toure', 'prenom' => 'Seydou', 'genre' => 'F', 'age' => 23, 'telephone' => '71320259', 'groupe_sanguin' => 'AB-', 'adresse' => "Niamakoro, Bamako"],
            ['nom' => 'Toure', 'prenom' => 'Seydou', 'genre' => 'M', 'age' => 1, 'telephone' => '71332160', 'groupe_sanguin' => 'B-', 'adresse' => "Kalaban Coura, Bamako"],
            ['nom' => 'Coulibaly', 'prenom' => 'Seydou', 'genre' => 'M', 'age' => 53, 'telephone' => '79846721', 'groupe_sanguin' => 'AB+', 'adresse' => "Sabalibougou, Bamako"],
            ['nom' => 'Keita', 'prenom' => 'Kadidia', 'genre' => 'M', 'age' => 84, 'telephone' => '75357167', 'groupe_sanguin' => 'AB+', 'adresse' => "Niamakoro, Bamako"],
            ['nom' => 'Sidibe', 'prenom' => 'Bakary', 'genre' => 'M', 'age' => 88, 'telephone' => '73835091', 'groupe_sanguin' => 'O+', 'adresse' => "Sabalibougou, Bamako"],
            ['nom' => 'Diallo', 'prenom' => 'Youssouf', 'genre' => 'M', 'age' => 82, 'telephone' => '74715700', 'groupe_sanguin' => 'AB-', 'adresse' => "Sogoniko, Bamako"],
            ['nom' => 'Barry', 'prenom' => 'Salimata', 'genre' => 'F', 'age' => 53, 'telephone' => '75671928', 'groupe_sanguin' => 'AB+', 'adresse' => "Banankabougou, Bamako"],
            ['nom' => 'Sissoko', 'prenom' => 'Kadidia', 'genre' => 'F', 'age' => 69, 'telephone' => '75221074', 'groupe_sanguin' => 'O-', 'adresse' => "ACI 2000, Bamako"],
            ['nom' => 'Diarra', 'prenom' => 'Aissata', 'genre' => 'M', 'age' => 87, 'telephone' => '77239459', 'groupe_sanguin' => 'O+', 'adresse' => "Lafiabougou, Bamako"],
            ['nom' => 'Coulibaly', 'prenom' => 'Aminata', 'genre' => 'F', 'age' => 82, 'telephone' => '76877760', 'groupe_sanguin' => 'O-', 'adresse' => "ACI 2000, Bamako"],
            ['nom' => 'Camara', 'prenom' => 'Mariam', 'genre' => 'M', 'age' => 34, 'telephone' => '75466187', 'groupe_sanguin' => 'O-', 'adresse' => "Sabalibougou, Bamako"],
            ['nom' => 'Toure', 'prenom' => 'Abdoulaye', 'genre' => 'F', 'age' => 89, 'telephone' => '79564041', 'groupe_sanguin' => 'AB-', 'adresse' => "Sogoniko, Bamako"],
            ['nom' => 'Keita', 'prenom' => 'Seydou', 'genre' => 'F', 'age' => 54, 'telephone' => '71049820', 'groupe_sanguin' => 'A-', 'adresse' => "Kalaban Coura, Bamako"],
            ['nom' => 'Sissoko', 'prenom' => 'Salimata', 'genre' => 'M', 'age' => 13, 'telephone' => '77678438', 'groupe_sanguin' => 'A-', 'adresse' => "Missabougou, Bamako"],
            ['nom' => 'Sangare', 'prenom' => 'Moussa', 'genre' => 'F', 'age' => 46, 'telephone' => '77752391', 'groupe_sanguin' => 'B+', 'adresse' => "Banankabougou, Bamako"],
            ['nom' => 'Toure', 'prenom' => 'Oumar', 'genre' => 'F', 'age' => 33, 'telephone' => '76698056', 'groupe_sanguin' => 'B-', 'adresse' => "Badalabougou, Bamako"],
            ['nom' => 'Maiga', 'prenom' => 'Bakary', 'genre' => 'F', 'age' => 87, 'telephone' => '73912014', 'groupe_sanguin' => 'B-', 'adresse' => "Magnambougou, Bamako"],
            ['nom' => 'Coulibaly', 'prenom' => 'Hawa', 'genre' => 'M', 'age' => 35, 'telephone' => '78489636', 'groupe_sanguin' => 'AB+', 'adresse' => "Banankabougou, Bamako"],
            ['nom' => 'Camara', 'prenom' => 'Aissata', 'genre' => 'M', 'age' => 85, 'telephone' => '78267369', 'groupe_sanguin' => 'B+', 'adresse' => "ACI 2000, Bamako"],
            ['nom' => 'Sissoko', 'prenom' => 'Youssouf', 'genre' => 'M', 'age' => 63, 'telephone' => '78372174', 'groupe_sanguin' => 'B-', 'adresse' => "Niamakoro, Bamako"],
            ['nom' => 'Coulibaly', 'prenom' => 'Oumar', 'genre' => 'F', 'age' => 45, 'telephone' => '74053405', 'groupe_sanguin' => 'AB-', 'adresse' => "Missabougou, Bamako"],
            ['nom' => 'Toure', 'prenom' => 'Salimata', 'genre' => 'F', 'age' => 65, 'telephone' => '75523668', 'groupe_sanguin' => 'A+', 'adresse' => "Sogoniko, Bamako"],
            ['nom' => 'Sissoko', 'prenom' => 'Issa', 'genre' => 'M', 'age' => 10, 'telephone' => '73547692', 'groupe_sanguin' => 'B+', 'adresse' => "Banankabougou, Bamako"],
            ['nom' => 'Barry', 'prenom' => 'Bakary', 'genre' => 'F', 'age' => 78, 'telephone' => '77157342', 'groupe_sanguin' => 'B+', 'adresse' => "Lafiabougou, Bamako"],
            ['nom' => 'Sangare', 'prenom' => 'Hawa', 'genre' => 'F', 'age' => 17, 'telephone' => '76328676', 'groupe_sanguin' => 'O+', 'adresse' => "Kalaban Coura, Bamako"],
            ['nom' => 'Diarra', 'prenom' => 'Aminata', 'genre' => 'M', 'age' => 10, 'telephone' => '79060374', 'groupe_sanguin' => 'B+', 'adresse' => "Magnambougou, Bamako"],
            ['nom' => 'Konate', 'prenom' => 'Salimata', 'genre' => 'F', 'age' => 49, 'telephone' => '71128051', 'groupe_sanguin' => 'B-', 'adresse' => "Yirimadio, Bamako"],
            ['nom' => 'Konate', 'prenom' => 'Aminata', 'genre' => 'F', 'age' => 63, 'telephone' => '73728297', 'groupe_sanguin' => 'A-', 'adresse' => "Magnambougou, Bamako"],
            ['nom' => 'Konate', 'prenom' => 'Moussa', 'genre' => 'F', 'age' => 18, 'telephone' => '73156343', 'groupe_sanguin' => 'AB+', 'adresse' => "ACI 2000, Bamako"],
            ['nom' => 'Cisse', 'prenom' => 'Aminata', 'genre' => 'F', 'age' => 55, 'telephone' => '75575129', 'groupe_sanguin' => 'B-', 'adresse' => "Badalabougou, Bamako"],
            ['nom' => 'Barry', 'prenom' => 'Fatoumata', 'genre' => 'F', 'age' => 19, 'telephone' => '71393714', 'groupe_sanguin' => 'O+', 'adresse' => "Sabalibougou, Bamako"],
            ['nom' => 'Cisse', 'prenom' => 'Oumar', 'genre' => 'M', 'age' => 11, 'telephone' => '74234642', 'groupe_sanguin' => 'B-', 'adresse' => "Hamdallaye, Bamako"],
            ['nom' => 'Keita', 'prenom' => 'Issa', 'genre' => 'F', 'age' => 46, 'telephone' => '78782197', 'groupe_sanguin' => 'AB+', 'adresse' => "Kalaban Coura, Bamako"],
            ['nom' => 'Traore', 'prenom' => 'Abdoulaye', 'genre' => 'M', 'age' => 33, 'telephone' => '77906871', 'groupe_sanguin' => 'O+', 'adresse' => "Badalabougou, Bamako"],
            ['nom' => 'Sangare', 'prenom' => 'Moussa', 'genre' => 'F', 'age' => 21, 'telephone' => '76838759', 'groupe_sanguin' => 'O-', 'adresse' => "Sabalibougou, Bamako"],
            ['nom' => 'Diallo', 'prenom' => 'Abdoulaye', 'genre' => 'M', 'age' => 72, 'telephone' => '74870791', 'groupe_sanguin' => 'O-', 'adresse' => "Yirimadio, Bamako"],
            ['nom' => 'Maiga', 'prenom' => 'Fatoumata', 'genre' => 'F', 'age' => 84, 'telephone' => '79806299', 'groupe_sanguin' => 'AB-', 'adresse' => "Sogoniko, Bamako"],
            ['nom' => 'Diarra', 'prenom' => 'Moussa', 'genre' => 'F', 'age' => 14, 'telephone' => '78038441', 'groupe_sanguin' => 'O+', 'adresse' => "Magnambougou, Bamako"],
            ['nom' => 'Diarra', 'prenom' => 'Salimata', 'genre' => 'M', 'age' => 14, 'telephone' => '75775802', 'groupe_sanguin' => 'O-', 'adresse' => "Magnambougou, Bamako"],
            ['nom' => 'Keita', 'prenom' => 'Aminata', 'genre' => 'M', 'age' => 81, 'telephone' => '77064135', 'groupe_sanguin' => 'B-', 'adresse' => "Magnambougou, Bamako"],
            ['nom' => 'Sissoko', 'prenom' => 'Abdoulaye', 'genre' => 'M', 'age' => 56, 'telephone' => '73169060', 'groupe_sanguin' => 'A-', 'adresse' => "ACI 2000, Bamako"],
            ['nom' => 'Konate', 'prenom' => 'Fatoumata', 'genre' => 'F', 'age' => 76, 'telephone' => '71920598', 'groupe_sanguin' => 'A-', 'adresse' => "Banankabougou, Bamako"],
            ['nom' => 'Barry', 'prenom' => 'Youssouf', 'genre' => 'M', 'age' => 59, 'telephone' => '77645825', 'groupe_sanguin' => 'B-', 'adresse' => "Missabougou, Bamako"],
            ['nom' => 'Camara', 'prenom' => 'Oumar', 'genre' => 'F', 'age' => 64, 'telephone' => '74668280', 'groupe_sanguin' => 'O-', 'adresse' => "ACI 2000, Bamako"],
            ['nom' => 'Sissoko', 'prenom' => 'Seydou', 'genre' => 'F', 'age' => 76, 'telephone' => '73119486', 'groupe_sanguin' => 'O+', 'adresse' => "Sogoniko, Bamako"],
            ['nom' => 'Maiga', 'prenom' => 'Oumar', 'genre' => 'M', 'age' => 73, 'telephone' => '72186006', 'groupe_sanguin' => 'A-', 'adresse' => "ACI 2000, Bamako"],
            ['nom' => 'Sissoko', 'prenom' => 'Aissata', 'genre' => 'M', 'age' => 20, 'telephone' => '74396721', 'groupe_sanguin' => 'O-', 'adresse' => "Missabougou, Bamako"],
            ['nom' => 'Konate', 'prenom' => 'Salimata', 'genre' => 'M', 'age' => 27, 'telephone' => '79720665', 'groupe_sanguin' => 'O-', 'adresse' => "Yirimadio, Bamako"],
            ['nom' => 'Sangare', 'prenom' => 'Issa', 'genre' => 'M', 'age' => 85, 'telephone' => '75659809', 'groupe_sanguin' => 'B-', 'adresse' => "Sogoniko, Bamako"],
            ['nom' => 'Konate', 'prenom' => 'Bakary', 'genre' => 'F', 'age' => 62, 'telephone' => '77326393', 'groupe_sanguin' => 'A-', 'adresse' => "Niamakoro, Bamako"],
            ['nom' => 'Konate', 'prenom' => 'Bakary', 'genre' => 'F', 'age' => 14, 'telephone' => '76675409', 'groupe_sanguin' => 'A-', 'adresse' => "Magnambougou, Bamako"],
            ['nom' => 'Diarra', 'prenom' => 'Mariam', 'genre' => 'F', 'age' => 23, 'telephone' => '76286487', 'groupe_sanguin' => 'A-', 'adresse' => "Hamdallaye, Bamako"],
            ['nom' => 'Barry', 'prenom' => 'Issa', 'genre' => 'M', 'age' => 40, 'telephone' => '74556522', 'groupe_sanguin' => 'O+', 'adresse' => "Banankabougou, Bamako"],
            ['nom' => 'Traore', 'prenom' => 'Aminata', 'genre' => 'F', 'age' => 42, 'telephone' => '73131888', 'groupe_sanguin' => 'B+', 'adresse' => "Missabougou, Bamako"],
            ['nom' => 'Dembele', 'prenom' => 'Abdoulaye', 'genre' => 'M', 'age' => 81, 'telephone' => '74016799', 'groupe_sanguin' => 'O+', 'adresse' => "Kalaban Coura, Bamako"],
            ['nom' => 'Sangare', 'prenom' => 'Kadidia', 'genre' => 'F', 'age' => 87, 'telephone' => '79362595', 'groupe_sanguin' => 'AB+', 'adresse' => "Kalaban Coura, Bamako"],
            ['nom' => 'Keita', 'prenom' => 'Aminata', 'genre' => 'M', 'age' => 74, 'telephone' => '71080615', 'groupe_sanguin' => 'AB-', 'adresse' => "Banankabougou, Bamako"],
            ['nom' => 'Keita', 'prenom' => 'Bakary', 'genre' => 'M', 'age' => 30, 'telephone' => '77169202', 'groupe_sanguin' => 'A+', 'adresse' => "Sogoniko, Bamako"],
            ['nom' => 'Sangare', 'prenom' => 'Fatoumata', 'genre' => 'M', 'age' => 38, 'telephone' => '74905218', 'groupe_sanguin' => 'O+', 'adresse' => "Missabougou, Bamako"],
            ['nom' => 'Sidibe', 'prenom' => 'Youssouf', 'genre' => 'M', 'age' => 28, 'telephone' => '71313288', 'groupe_sanguin' => 'A-', 'adresse' => "Magnambougou, Bamako"],
            ['nom' => 'Diallo', 'prenom' => 'Issa', 'genre' => 'F', 'age' => 55, 'telephone' => '72151441', 'groupe_sanguin' => 'O-', 'adresse' => "Badalabougou, Bamako"],
            ['nom' => 'Camara', 'prenom' => 'Oumar', 'genre' => 'M', 'age' => 5, 'telephone' => '72723250', 'groupe_sanguin' => 'O+', 'adresse' => "Kalaban Coura, Bamako"],
            ['nom' => 'Barry', 'prenom' => 'Kadidia', 'genre' => 'M', 'age' => 65, 'telephone' => '73312636', 'groupe_sanguin' => 'B-', 'adresse' => "Kalaban Coura, Bamako"],
            ['nom' => 'Maiga', 'prenom' => 'Ibrahim', 'genre' => 'M', 'age' => 42, 'telephone' => '71200484', 'groupe_sanguin' => 'B-', 'adresse' => "Yirimadio, Bamako"],
            ['nom' => 'Cisse', 'prenom' => 'Mariam', 'genre' => 'M', 'age' => 5, 'telephone' => '75035448', 'groupe_sanguin' => 'AB-', 'adresse' => "Niamakoro, Bamako"],
            ['nom' => 'Camara', 'prenom' => 'Aminata', 'genre' => 'M', 'age' => 90, 'telephone' => '73708947', 'groupe_sanguin' => 'B+', 'adresse' => "Kalaban Coura, Bamako"],
            ['nom' => 'Diallo', 'prenom' => 'Fatoumata', 'genre' => 'M', 'age' => 34, 'telephone' => '77560427', 'groupe_sanguin' => 'O-', 'adresse' => "Kalaban Coura, Bamako"],
            ['nom' => 'Sidibe', 'prenom' => 'Issa', 'genre' => 'M', 'age' => 40, 'telephone' => '72837316', 'groupe_sanguin' => 'O+', 'adresse' => "Sogoniko, Bamako"],
            ['nom' => 'Cisse', 'prenom' => 'Salimata', 'genre' => 'M', 'age' => 22, 'telephone' => '75546261', 'groupe_sanguin' => 'B+', 'adresse' => "Badalabougou, Bamako"],
            ['nom' => 'Cisse', 'prenom' => 'Hawa', 'genre' => 'F', 'age' => 24, 'telephone' => '79364937', 'groupe_sanguin' => 'AB+', 'adresse' => "Niamakoro, Bamako"],
            ['nom' => 'Traore', 'prenom' => 'Ibrahim', 'genre' => 'M', 'age' => 28, 'telephone' => '72214094', 'groupe_sanguin' => 'B-', 'adresse' => "Missabougou, Bamako"],
            ['nom' => 'Traore', 'prenom' => 'Abdoulaye', 'genre' => 'F', 'age' => 65, 'telephone' => '71793982', 'groupe_sanguin' => 'B-', 'adresse' => "Niamakoro, Bamako"],
            ['nom' => 'Sangare', 'prenom' => 'Fatoumata', 'genre' => 'F', 'age' => 15, 'telephone' => '75390611', 'groupe_sanguin' => 'AB-', 'adresse' => "Badalabougou, Bamako"],
            ['nom' => 'Cisse', 'prenom' => 'Oumar', 'genre' => 'M', 'age' => 41, 'telephone' => '78578425', 'groupe_sanguin' => 'AB+', 'adresse' => "Niamakoro, Bamako"],
            ['nom' => 'Konate', 'prenom' => 'Kadidia', 'genre' => 'M', 'age' => 37, 'telephone' => '77890268', 'groupe_sanguin' => 'A+', 'adresse' => "Hamdallaye, Bamako"],
            ['nom' => 'Cisse', 'prenom' => 'Hawa', 'genre' => 'F', 'age' => 7, 'telephone' => '71939338', 'groupe_sanguin' => 'O-', 'adresse' => "Niamakoro, Bamako"],
        ];

        foreach ($patients as $patient) {
            $patient['uuid'] = (string) Str::uuid();
            $patient['created_at'] = now();
            $patient['updated_at'] = now();

            DB::table('patients')->updateOrInsert(
                ['telephone' => $patient['telephone']],
                $patient
            );
        }
    }
}
