<?php

namespace Database\Seeders;
use Illuminate\Support\Str;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProtocoleTraitementSeeder extends Seeder
{
    public function run(): void
    {
        $maladieIds = DB::table('maladies')->pluck('id', 'nom')->toArray();
        
        $protocoles = [
            // ==================== PALUDISME ====================
            [
                'maladie_id' => $maladieIds['Paludisme simple'],
                'titre' => 'Traitement du paludisme non compliqué à P. falciparum',
                'signes' => 'Fièvre, céphalées, fatigue, frissons, sueurs, douleurs musculaires et articulaires',
                'diagnostics' => 'Goutte épaisse ou test de diagnostic rapide (TDR) positif',
                'germes_nourrisson' => 'Plasmodium falciparum, Plasmodium vivax, Plasmodium ovale, Plasmodium malariae',
                'germes_adulte' => 'Plasmodium falciparum, Plasmodium vivax, Plasmodium ovale, Plasmodium malariae',
                'traitement_principal' => 'Artéméther/Luméfantrine (ACT)',
                'posologie_principale' => 'Selon le poids : 2 prises/jour pendant 3 jours. 5-15 kg: 1 cp 20/120mg par prise; 15-25 kg: 2 cp; 25-35 kg: 3 cp; ≥35 kg: 4 cp',
                'traitement_alternatif' => 'Artésunate/Amodiaquine (AS/AQ)',
                'posologie_alternative' => 'Selon le poids : 1 fois/jour pendant 3 jours. 4,5-9 kg: 1 cp 25/67,5mg; 9-18 kg: 1 cp 50/135mg; 18-36 kg: 1 cp 100/270mg; ≥36 kg: 2 cp 100/270mg',
                'remarques' => 'Prendre les comprimés au cours des repas ou avec une boisson riche en graisse (lait). En cas de vomissements dans les 30 minutes, reprendre la même dose.',
                'uuid' => (string) Str::uuid(), 'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'maladie_id' => $maladieIds['Paludisme grave'],
                'titre' => 'Traitement du paludisme grave (après artésunate IV)',
                'signes' => 'Altération de la conscience, détresse respiratoire, convulsions, choc, ictère, hémoglobinurie',
                'diagnostics' => 'Goutte épaisse positive + signes de gravité',
                'germes_nourrisson' => 'Plasmodium falciparum',
                'germes_adulte' => 'Plasmodium falciparum',
                'traitement_principal' => 'Artéméther/Luméfantrine (ACT)',
                'posologie_principale' => 'Même posologie que paludisme non compliqué, à démarrer 8-12h après la dernière injection d\'artésunate',
                'traitement_alternatif' => 'Quinine',
                'posologie_alternative' => 'Adulte: 600mg 3x/jour pendant 7 jours; Enfant: 10mg/kg 3x/jour pendant 7 jours',
                'remarques' => 'Ne pas utiliser la quinine si le patient a déjà reçu de la quinine ou méfloquine dans les 24h',
                'uuid' => (string) Str::uuid(), 'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'maladie_id' => $maladieIds['Paludisme à P. vivax'] ?? $maladieIds['Paludisme simple'],
                'titre' => 'Traitement du paludisme à P. vivax (avec radicalisation par primaquine)',
                'signes' => 'Accès fébrile périodique, splénomégalie, anémie progressive',
                'diagnostics' => 'Frottis : Plasmodium vivax, TDR +/-, sérologie',
                'germes_nourrisson' => 'Plasmodium vivax',
                'germes_adulte' => 'Plasmodium vivax',
                'traitement_principal' => 'Chloroquine + Primaquine (guérison radicale)',
                'posologie_principale' => 'Chloroquine 25mg/kg en 3 jours; Primaquine 0,25mg/kg/jour pendant 14 jours',
                'traitement_alternatif' => 'Artéméther/Luméfantrine',
                'posologie_alternative' => 'Même posologie que paludisme non compliqué x3 jours',
                'remarques' => 'Dosage G6PD requis avant primaquine. Contre-indiqué si déficit G6PD sévère.',
                'uuid' => (string) Str::uuid(), 'created_at' => now(),
                'updated_at' => now()
            ],
            
            // ==================== INFECTIONS RESPIRATOIRES ====================
            [
                'maladie_id' => $maladieIds['Pneumonie simple'],
                'titre' => 'Pneumonie sans signes de gravité',
                'signes' => 'Toux, fièvre, tachypnée, signes de lutte respiratoire (tirage, gémissements)',
                'diagnostics' => 'Examen clinique, saturation O2 > 90%, pas de signes de détresse respiratoire sévère',
                'germes_nourrisson' => 'Streptococcus pneumoniae, Haemophilus influenzae, Staphylococcus aureus, virus respiratoires',
                'germes_adulte' => 'Streptococcus pneumoniae, Mycoplasma pneumoniae, Chlamydia pneumoniae, virus',
                'traitement_principal' => 'Amoxicilline',
                'posologie_principale' => 'Adulte: 1g 3x/jour pendant 5 jours; Enfant: 30mg/kg 3x/jour pendant 5 jours',
                'traitement_alternatif' => 'Co-trimoxazole',
                'posologie_alternative' => 'Adulte: 800/160mg 2x/jour pendant 5 jours; Enfant: 20/4mg/kg 2x/jour pendant 5 jours',
                'remarques' => 'En cas d\'allergie aux pénicillines, utiliser le co-trimoxazole ou l\'azithromycine',
                'uuid' => (string) Str::uuid(), 'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'maladie_id' => $maladieIds['Pneumonie sévère'],
                'titre' => 'Pneumonie sévère (hospitalisation)',
                'signes' => 'Détresse respiratoire sévère, hypoxémie (SpO2 < 90%), cyanose, impossibilité de boire',
                'diagnostics' => 'Examen clinique + saturation O2, radiographie thoracique',
                'germes_nourrisson' => 'Streptococcus pneumoniae, Staphylococcus aureus, Klebsiella pneumoniae',
                'germes_adulte' => 'Streptococcus pneumoniae, Legionella pneumophila, bactéries Gram négatif',
                'traitement_principal' => 'Ceftriaxone IV puis relais Amoxicilline',
                'posologie_principale' => 'Ceftriaxone: 50-100mg/kg/jour IV pendant 3-5 jours puis Amoxicilline: 1g 3x/jour PO pour compléter 7-10 jours',
                'traitement_alternatif' => 'Céfotaxime IV puis relais Co-trimoxazole',
                'posologie_alternative' => 'Céfotaxime: 50mg/kg toutes les 8h IV pendant 3-5 jours puis Co-trimoxazole: 800/160mg 2x/jour PO',
                'remarques' => 'Oxygénothérapie si SpO2 < 90%',
                'uuid' => (string) Str::uuid(), 'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'maladie_id' => $maladieIds['Grippe'] ?? $maladieIds['Pneumonie simple'],
                'titre' => 'Traitement de la grippe saisonnière',
                'signes' => 'Fièvre brutale, céphalées, myalgies, toux sèche, fatigue intense',
                'diagnostics' => 'Tableau clinique, test rapide grippal (TDR) si disponible',
                'germes_nourrisson' => 'Virus influenza A et B',
                'germes_adulte' => 'Virus influenza A et B',
                'traitement_principal' => 'Oseltamivir (Tamiflu)',
                'posologie_principale' => 'Adulte: 75mg 2x/jour pendant 5 jours; Enfant: selon poids 2mg/kg 2x/jour',
                'traitement_alternatif' => 'Soins symptomatiques seuls (si antiviral non indiqué)',
                'posologie_alternative' => 'Paracétamol, réhydratation, repos',
                'remarques' => 'Efficace si démarré dans les 48h suivant le début des symptômes',
                'uuid' => (string) Str::uuid(), 'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'maladie_id' => $maladieIds['Coqueluche'] ?? $maladieIds['Pneumonie simple'],
                'titre' => 'Traitement de la coqueluche',
                'signes' => 'Toux quinteuse nocturne, quintes avec reprise inspiratoire (« chant du coq »), vomissements post-tussifs',
                'diagnostics' => 'Tableau clinique évocateur, culture nasopharyngée, PCR si disponible',
                'germes_nourrisson' => 'Bordetella pertussis, Bordetella parapertussis',
                'germes_adulte' => 'Bordetella pertussis',
                'traitement_principal' => 'Azithromycine',
                'posologie_principale' => 'Adulte: 500mg J1 puis 250mg J2-J5; Enfant: 10mg/kg J1 puis 5mg/kg J2-J5',
                'traitement_alternatif' => 'Érythromycine ou Clarithromycine',
                'posologie_alternative' => 'Érythromycine: 40-50mg/kg/jour en 4 prises pendant 14 jours',
                'remarques' => 'Isolement du patient, déclaration obligatoire, antibiotiques inutiles après 3 semaines de toux',
                'uuid' => (string) Str::uuid(), 'created_at' => now(),
                'updated_at' => now()
            ],
            
            // ==================== HYPERTENSION ARTÉRIELLE ====================
            [
                'maladie_id' => $maladieIds['Hypertension artérielle'],
                'titre' => 'Traitement de l\'hypertension artérielle essentielle',
                'signes' => 'PA > 140/90 mmHg au repos, céphalées occipitales, vertiges, parfois asymptomatique',
                'diagnostics' => 'Mesure de la pression artérielle à plusieurs reprises, bilan biologique (créatininémie, glycémie, bilan lipidique)',
                'germes_nourrisson' => null,
                'germes_adulte' => null,
                'traitement_principal' => 'Amlodipine ou Énalapril',
                'posologie_principale' => 'Amlodipine: 5-10mg 1x/jour; Énalapril: 5-20mg 1-2x/jour',
                'traitement_alternatif' => 'Hydrochlorothiazide ou Bisoprolol',
                'posologie_alternative' => 'Hydrochlorothiazide: 12,5-25mg 1x/jour; Bisoprolol: 5-10mg 1x/jour',
                'remarques' => 'Traitement à vie. Surveillance de la TA, fonction rénale et électrolytes. Mesures hygiéno-diététiques associées.',
                'uuid' => (string) Str::uuid(), 'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'maladie_id' => $maladieIds['Hypertension gravidique'],
                'titre' => 'Hypertension gravidique / Pré-éclampsie',
                'signes' => 'PA ≥ 140/90 mmHg après 20 semaines de grossesse, protéinurie, œdèmes',
                'diagnostics' => 'Mesure TA, bandelette urinaire (protéinurie), bilan biologique',
                'germes_nourrisson' => null,
                'germes_adulte' => null,
                'traitement_principal' => 'Labétalol ou Méthyldopa',
                'posologie_principale' => 'Labétalol: 100-200mg 2x/jour; Méthyldopa: 250mg 2-3x/jour jusqu\'à 1,5g/jour',
                'traitement_alternatif' => 'Nifédipine (forme à libération prolongée)',
                'posologie_alternative' => 'Nifédipine LP: 20-60mg 1x/jour',
                'remarques' => 'Surveillance étroite de la TA maternelle et du rythme cardiaque fœtal. Ne pas utiliser d\'IEC (contre-indiqués pendant la grossesse)',
                'uuid' => (string) Str::uuid(), 'created_at' => now(),
                'updated_at' => now()
            ],
            
            // ==================== DIABÈTE ====================
            [
                'maladie_id' => $maladieIds['Diabète de type 2'],
                'titre' => 'Traitement du diabète de type 2',
                'signes' => 'Polyurie, polydipsie, polyphagie, amaigrissement, fatigue, troubles visuels',
                'diagnostics' => 'Glycémie à jeun ≥ 7,0 mmol/L ou glycémie aléatoire ≥ 11,1 mmol/L ou HbA1c ≥ 6,5%',
                'germes_nourrisson' => null,
                'germes_adulte' => null,
                'traitement_principal' => 'Metformine',
                'posologie_principale' => '500mg 1x/jour le matin (semaine 1) puis 500mg 2x/jour (semaine 2) puis augmenter jusqu\'à 1g 2x/jour si nécessaire',
                'traitement_alternatif' => 'Glibenclamide ou Gliclazide',
                'posologie_alternative' => 'Glibenclamide: 2,5-5mg 1-2x/jour; Gliclazide: 40-80mg 1-2x/jour',
                'remarques' => 'Associer mesures hygiéno-diététiques et activité physique. Surveillance de la glycémie et de l\'HbA1c.',
                'uuid' => (string) Str::uuid(), 'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'maladie_id' => $maladieIds['Diabète de type 1'] ?? $maladieIds['Diabète de type 2'],
                'titre' => 'Traitement du diabète de type 1 (insulinothérapie)',
                'signes' => 'Polyurie, polydipsie, polyphagie, amaigrissement rapide, acido-cétose possible',
                'diagnostics' => 'Glycémie ≥ 11,1 mmol/L, HbA1c ≥ 6,5%, corps cétoniques élevés',
                'germes_nourrisson' => null,
                'germes_adulte' => null,
                'traitement_principal' => 'Insuline rapide + Insuline NPH (basale-bolus)',
                'posologie_principale' => 'Insuline rapide: 3-4 injections/jour avant repas; Insuline NPH: 1-2 injections/jour selon schéma',
                'traitement_alternatif' => 'Pompe à insuline',
                'posologie_alternative' => 'Administration continue sous-cutanée',
                'remarques' => 'Éducation thérapeutique essentielle. Automonitoring glycémique 3-4x/jour.',
                'uuid' => (string) Str::uuid(), 'created_at' => now(),
                'updated_at' => now()
            ],
            
            // ==================== GASTRO-ENTÉRITE ====================
            [
                'maladie_id' => $maladieIds['Gastro-entérite'],
                'titre' => 'Traitement de la gastro-entérite aiguë',
                'signes' => 'Diarrhée aqueuse, vomissements, douleurs abdominales, nausées, fièvre modérée',
                'diagnostics' => 'Examen clinique, évaluation du degré de déshydratation',
                'germes_nourrisson' => 'Rotavirus, Escherichia coli, norovirus',
                'germes_adulte' => 'Campylobacter jejuni, Salmonella, Shigella, norovirus',
                'traitement_principal' => 'SRO + Zinc (enfant)',
                'posologie_principale' => 'SRO: selon le plan A ou B OMS; Zinc: 20mg/jour (10mg si <6 mois) pendant 10 jours',
                'traitement_alternatif' => 'Métronidazole (si Giardia ou C. difficile suspecté)',
                'posologie_alternative' => 'Adulte: 500mg 3x/jour pendant 5-7 jours; Enfant: 15mg/kg 3x/jour',
                'remarques' => 'La réhydratation est la priorité. Ne pas utiliser d\'antidiarrhéiques chez l\'enfant. Éviter le lopéramide sauf cas particuliers.',
                'uuid' => (string) Str::uuid(), 'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'maladie_id' => $maladieIds['Choléra'] ?? $maladieIds['Gastro-entérite'],
                'titre' => 'Traitement du choléra',
                'signes' => 'Diarrhée liquide profuse (« eau de riz »), vomissements, déshydratation rapide sévère',
                'diagnostics' => 'Examen clinique (déshydratation), coproculture Vibrio cholerae',
                'germes_nourrisson' => 'Vibrio cholerae O1 et O139',
                'germes_adulte' => 'Vibrio cholerae O1 et O139',
                'traitement_principal' => 'SRO optimisée (OMS) + Réhydratation IV (Ringer Lactate)',
                'posologie_principale' => 'SRO: 1 sachet/L jusqu\'à cessation des selles; Ringer: 100ml/kg en 3h puis maintien',
                'traitement_alternatif' => 'Doxycycline ou Azithromycine (antibioprophylaxie non recommandée en routine)',
                'posologie_alternative' => 'Doxycycline: 300mg dose unique; Azithromycine: 1g dose unique',
                'remarques' => 'Urgence de réhydratation. Déclaration obligatoire. Mesures d\'hygiène pour éviter la transmission.',
                'uuid' => (string) Str::uuid(), 'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'maladie_id' => $maladieIds['Amibiase intestinale'] ?? $maladieIds['Gastro-entérite'],
                'titre' => 'Traitement de l\'amibiase intestinale (Entamoeba histolytica)',
                'signes' => 'Diarrhée sanglante (dysenterie amibienne), douleurs abdominales, ténesme',
                'diagnostics' => 'Examen parasitologique des selles, coloscopie si besoin',
                'germes_nourrisson' => 'Entamoeba histolytica',
                'germes_adulte' => 'Entamoeba histolytica',
                'traitement_principal' => 'Métronidazole + Diloxanide furoate',
                'posologie_principale' => 'Métronidazole: 500-750mg 3x/jour pendant 5-7 jours puis Diloxanide: 500mg 3x/jour pendant 10 jours',
                'traitement_alternatif' => 'Tinidazole + Diloxanide',
                'posologie_alternative' => 'Tinidazole: 2g/jour pendant 5 jours puis Diloxanide',
                'remarques' => 'Différencier de Giardia (traité par métronidazole seul).',
                'uuid' => (string) Str::uuid(), 'created_at' => now(),
                'updated_at' => now()
            ],
            
            // ==================== TYPHOÏDE ====================
            [
                'maladie_id' => $maladieIds['Typhoïde'],
                'titre' => 'Traitement de la fièvre typhoïde',
                'signes' => 'Fièvre élevée prolongée en plateau, céphalées, douleurs abdominales, constipation puis diarrhée, taches rosées',
                'diagnostics' => 'Hémoculture, coproculture, test de Widal-Felix (moins fiable)',
                'germes_nourrisson' => 'Salmonella enterica serovar Typhi, Salmonella Paratyphi',
                'germes_adulte' => 'Salmonella enterica serovar Typhi, Salmonella Paratyphi',
                'traitement_principal' => 'Ciprofloxacine (si souche sensible)',
                'posologie_principale' => 'Adulte: 500mg 2x/jour pendant 10-14 jours; Enfant: 15mg/kg 2x/jour',
                'traitement_alternatif' => 'Ceftriaxone IV ou Azithromycine',
                'posologie_alternative' => 'Ceftriaxone: 50-80mg/kg/jour IV pendant 10-14 jours; Azithromycine: 1g J1 puis 500mg/jour J2-J7',
                'remarques' => 'La résistance aux fluoroquinolones est fréquente. Adapter l\'antibiothérapie à l\'antibiogramme.',
                'uuid' => (string) Str::uuid(), 'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'maladie_id' => $maladieIds['Shigellose'] ?? $maladieIds['Typhoïde'],
                'titre' => 'Traitement de la shigellose',
                'signes' => 'Diarrhée sanglante et muqueuse, douleurs abdominales, fièvre, ténesme',
                'diagnostics' => 'Coproculture, examen direct',
                'germes_nourrisson' => 'Shigella dysenteriae, Shigella flexneri, Shigella sonnei',
                'germes_adulte' => 'Shigella spp.',
                'traitement_principal' => 'Ciprofloxacine',
                'posologie_principale' => 'Adulte: 500mg 2x/jour pendant 3 jours; Enfant: 15mg/kg 2x/jour',
                'traitement_alternatif' => 'Azithromycine ou Ceftriaxone',
                'posologie_alternative' => 'Azithromycine: 500mg J1 puis 250mg J2-J5; Ceftriaxone: 50mg/kg/jour',
                'remarques' => 'Isolement du patient. Déshydratation. Déclaration si shigellose dysentérique de type 1.',
                'uuid' => (string) Str::uuid(), 'created_at' => now(),
                'updated_at' => now()
            ],
            
            // ==================== DRÉPANOCYTOSE ====================
            [
                'maladie_id' => $maladieIds['Drépanocytose'],
                'titre' => 'Prévention des infections chez le drépanocytaire',
                'signes' => 'Anémie hémolytique, crises vaso-occlusives douloureuses, asplénie fonctionnelle',
                'diagnostics' => 'Électrophorèse de l\'hémoglobine (HbS > 50%)',
                'germes_nourrisson' => 'Streptococcus pneumoniae, Haemophilus influenzae, Salmonella, Mycoplasma',
                'germes_adulte' => 'Streptococcus pneumoniae, Salmonella, Escherichia coli',
                'traitement_principal' => 'Pénicilline V ou Amoxicilline (prophylaxie)',
                'posologie_principale' => 'Enfant < 3 ans: 125mg 2x/jour; Enfant 3-5 ans: 250mg 2x/jour; >5 ans: 500mg 2x/jour',
                'traitement_alternatif' => 'Érythromycine (si allergie pénicilline)',
                'posologie_alternative' => 'Enfant: 250mg 2x/jour',
                'remarques' => 'Prophylaxie recommandée jusqu\'à 5 ans minimum, à vie dans certaines recommandations. Vaccination anti-pneumocoque et anti-Hib obligatoire.',
                'uuid' => (string) Str::uuid(), 'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'maladie_id' => $maladieIds['Drépanocytose'],
                'titre' => 'Traitement de la crise vaso-occlusive drépanocytaire',
                'signes' => 'Douleurs osseuses, articulaires, abdominales ou thoraciques intenses, fièvre possible',
                'diagnostics' => 'Examen clinique, NFS, bilan inflammatoire',
                'germes_nourrisson' => null,
                'germes_adulte' => null,
                'traitement_principal' => 'Paracétamol + Ibuprofène + Hydratation',
                'posologie_principale' => 'Paracétamol: 1g 4x/jour; Ibuprofène: 400mg 3x/jour; Hydratation: 2-3L/jour PO ou IV',
                'traitement_alternatif' => 'Morphine (douleurs sévères)',
                'posologie_alternative' => 'Morphine LI: 10mg toutes les 4h selon la douleur',
                'remarques' => 'Hospitaliser si douleurs sévères, fièvre, syndrome thoracique aigu ou anémie sévère.',
                'uuid' => (string) Str::uuid(), 'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'maladie_id' => $maladieIds['Syndrome thoracique aigu'] ?? $maladieIds['Drépanocytose'],
                'titre' => 'Syndrome thoracique aigu (STA) - complication drépanocytaire',
                'signes' => 'Douleur thoracique, fièvre, toux, dyspnée, SpO2 < 90%, infiltrat radiologique',
                'diagnostics' => 'Examen clinique, radiographie thoracique, NFS, gaz du sang',
                'germes_nourrisson' => 'Streptococcus pneumoniae, Haemophilus influenzae, virus respiratoires',
                'germes_adulte' => 'Streptococcus pneumoniae, virus',
                'traitement_principal' => 'Oxygénothérapie + Antalgie + Antibiothérapie (Ceftriaxone + Azithromycine)',
                'posologie_principale' => 'O2 pour SpO2 > 95%; Antibiothérapie: Ceftriaxone 50mg/kg/jour + Azithromycine 10mg/kg/jour',
                'traitement_alternatif' => 'Échange transfusionnel (cas sévères)',
                'posologie_alternative' => 'Selon protocole transfusionnel',
                'remarques' => 'Urgence vitale. Hospitalisation en soins intensifs si SatO2 < 90%.',
                'uuid' => (string) Str::uuid(), 'created_at' => now(),
                'updated_at' => now()
            ],
            
            // ==================== VIH/SIDA ====================
            [
                'maladie_id' => $maladieIds['VIH/SIDA'],
                'titre' => 'Traitement antirétroviral de première ligne (adulte)',
                'signes' => 'Symptômes variables selon le stade: fièvre, adénopathies, amaigrissement, infections opportunistes',
                'diagnostics' => 'Sérologie VIH positive, CD4 < 500/mm³, charge virale élevée',
                'germes_nourrisson' => null,
                'germes_adulte' => 'VIH-1',
                'traitement_principal' => 'Ténofovir + Lamivudine + Dolutégravir (TLD)',
                'posologie_principale' => '1 comprimé (TDF 300mg + 3TC 300mg + DTG 50mg) 1x/jour',
                'traitement_alternatif' => 'Ténofovir + Lamivudine + Éfavirenz (TLE)',
                'posologie_alternative' => 'TDF 300mg + 3TC 300mg + EFV 600mg 1x/jour',
                'remarques' => 'Traitement à vie. Surveillance de la charge virale, CD4, fonction rénale (ténofovir). Adapter si co-infections.',
                'uuid' => (string) Str::uuid(), 'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'maladie_id' => $maladieIds['VIH/SIDA'],
                'titre' => 'Traitement antirétroviral 2ème ligne (adulte) - après échec du TLD',
                'signes' => 'Échec virologique sous TLD, charge virale > 1000 copies/mL malgré observance',
                'diagnostics' => 'Charge virale > 1000 copies/mL à 3 mois malgré adhésion optimale',
                'germes_nourrisson' => null,
                'germes_adulte' => 'VIH-1',
                'traitement_principal' => 'Darunavir/ritonavir + 2 INTI',
                'posologie_principale' => 'DRV/r 800/100mg 1x/jour + 2 INTI actifs (ex: TDF + 3TC si non utilisé)',
                'traitement_alternatif' => 'Lopinavir/ritonavir + INTI',
                'posologie_alternative' => 'LPV/r 400/100mg 2x/jour',
                'remarques' => 'Test de résistance recommandé avant changement. Renforcer l\'observance.',
                'uuid' => (string) Str::uuid(), 'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'maladie_id' => $maladieIds['PTME'] ?? $maladieIds['VIH/SIDA'],
                'titre' => 'PTME - Prévention de la transmission mère-enfant du VIH',
                'signes' => 'Femme enceinte VIH+, nouveau-né exposé',
                'diagnostics' => 'Sérologie VIH de la mère, PCR nourrisson à J48 et M6',
                'germes_nourrisson' => null,
                'germes_adulte' => null,
                'traitement_principal' => 'TLD chez la mère + Névirapine prophylactique nourrisson',
                'posologie_principale' => 'Mère: TLD dès que possible pendant la grossesse et l\'allaitement; Nourrisson: NVP 2mg/kg/jour pendant 6 semaines',
                'traitement_alternatif' => 'AZT 4mg/kg 2x/jour nourrisson',
                'posologie_alternative' => 'Pour les mères non éligibles TLD: AZT 300mg 2x/jour + 3TC 150mg 2x/jour',
                'remarques' => 'Allaitement maternel exclusif encouragé si mère sous TAR. PCR early infant diagnosis à 6 semaines.',
                'uuid' => (string) Str::uuid(), 'created_at' => now(),
                'updated_at' => now()
            ],
            
            // ==================== MÉNINGITE ====================
            [
                'maladie_id' => $maladieIds['Méningite'],
                'titre' => 'Traitement de la méningite bactérienne',
                'signes' => 'Fièvre élevée, céphalées intenses, raideur de la nuque, vomissements, photophobie, troubles de la conscience',
                'diagnostics' => 'Ponction lombaire, analyse du LCR, examen direct, culture, antigènes',
                'germes_nourrisson' => 'Streptococcus agalactiae, Escherichia coli, Listeria monocytogenes',
                'germes_adulte' => 'Neisseria meningitidis, Streptococcus pneumoniae, Haemophilus influenzae',
                'traitement_principal' => 'Ceftriaxone',
                'posologie_principale' => 'Adulte: 2g 2x/jour IV pendant 7-14 jours; Enfant: 50-100mg/kg 2x/jour IV',
                'traitement_alternatif' => 'Céfotaxime + Gentamicine (si allergie ceftriaxone)',
                'posologie_alternative' => 'Céfotaxime: 50mg/kg toutes les 6h IV; Gentamicine: 5-6mg/kg 1x/jour IV',
                'remarques' => 'Corticothérapie (dexaméthasone) recommandée avant la première dose d\'antibiotique en cas de suspicion de méningite à pneumocoque',
                'uuid' => (string) Str::uuid(), 'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'maladie_id' => $maladieIds['Méningite cryptococcique'] ?? $maladieIds['Méningite'],
                'titre' => 'Traitement de la méningite cryptococcique (Cryptococcus neoformans)',
                'signes' => 'Céphalées, fièvre, raideur de nuque, troubles de la conscience, coma possible',
                'diagnostics' => 'Ponction lombaire: LCR trouble, antigène cryptococcique positif, culture positive',
                'germes_nourrisson' => null,
                'germes_adulte' => 'Cryptococcus neoformans/gattii (souvent chez immunodéprimés, VIH)',
                'traitement_principal' => 'Amphotéricine B liposomale + Flucytosine (phase d\'induction)',
                'posologie_principale' => 'Amphotéricine B liposomale 3-4mg/kg/jour IV + Flucytosine 100mg/kg/jour en 4 prises pendant 2 semaines',
                'traitement_alternatif' => 'Amphotéricine B déoxycholate + Flucytosine',
                'posologie_alternative' => 'Amphotéricine B 0,7-1mg/kg/jour IV + Flucytosine 100mg/kg/jour',
                'remarques' => 'Patient VIH: traitement d\'induction 2 semaines puis consolidation Fluconazole 400mg/jour puis fluconazole 200mg/jour long terme. Répéter PL de contrôle.',
                'uuid' => (string) Str::uuid(), 'created_at' => now(),
                'updated_at' => now()
            ],
            
            // ==================== HÉPATITE B ====================
            [
                'maladie_id' => $maladieIds['Hépatite B'],
                'titre' => 'Traitement de l\'hépatite B chronique',
                'signes' => 'Fatigue, ictère, hépatomégalie, asymptomatique souvent',
                'diagnostics' => 'AgHBs positif > 6 mois, transaminases élevées, charge virale > 2000 UI/mL',
                'germes_nourrisson' => 'Virus de l\'hépatite B (VHB)',
                'germes_adulte' => 'Virus de l\'hépatite B (VHB)',
                'traitement_principal' => 'Ténofovir',
                'posologie_principale' => 'TDF 300mg 1x/jour',
                'traitement_alternatif' => 'Lamivudine (si ténofovir indisponible)',
                'posologie_alternative' => '3TC 100mg 1x/jour',
                'remarques' => 'Surveillance fonction hépatique, charge virale, marqueurs viraux. Traitement à vie.',
                'uuid' => (string) Str::uuid(), 'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'maladie_id' => $maladieIds['Hépatite C'] ?? $maladieIds['Hépatite B'],
                'titre' => 'Traitement de l\'hépatite C chronique',
                'signes' => 'Généralement asymptomatique, fatigue possible, ictère rare',
                'diagnostics' => 'Sérologie VHC positive, charge virale VHC positive, génotypage',
                'germes_nourrisson' => null,
                'germes_adulte' => 'Virus de l\'hépatite C (VHC genotypes 1-6)',
                'traitement_principal' => 'Sofosbuvir/Velpatasvir (associations pan-génotypiques)',
                'posologie_principale' => 'SOF/VEL 400/100mg 1 comprimé/jour pendant 12 semaines',
                'traitement_alternatif' => 'Ledipasvir/Sofosbuvir (génotype 1, 4, 5, 6)',
                'posologie_alternative' => 'LED/SOF 90/400mg 1 comprimé/jour pendant 8-12 semaines',
                'remarques' => 'VHC génotype 3 avec cirrhose: ajouter ribavirine. Dépistage et traitement des co-infections VIH/VHC.',
                'uuid' => (string) Str::uuid(), 'created_at' => now(),
                'updated_at' => now()
            ],
            
            // ==================== TUBERCULOSE ====================
            [
                'maladie_id' => $maladieIds['Tuberculose pulmonaire'] ?? $maladieIds['Tuberculose'] ?? 1,
                'titre' => 'Traitement de la tuberculose pulmonaire (protocole OMS 6 mois)',
                'signes' => 'Toux > 2 semaines, crachats, hémoptysies, fièvre vespérale, sueurs nocturnes, amaigrissement',
                'diagnostics' => 'Examen microscopique des crachats (BAAR), culture, GeneXpert, radiographie thoracique',
                'germes_nourrisson' => 'Mycobacterium tuberculosis complex',
                'germes_adulte' => 'Mycobacterium tuberculosis',
                'traitement_principal' => 'Rifampicine + Isoniazide + Pyrazinamide + Éthambutol (RHZE) puis RH',
                'posologie_principale' => 'Phase intensive (2 mois): Rifampicine 10mg/kg + Isoniazide 5mg/kg + Pyrazinamide 25mg/kg + Éthambutol 15mg/kg; Phase continuation (4 mois): Rifampicine + Isoniazide',
                'traitement_alternatif' => 'Associations à doses fixes (FDC) RH, RHZ, RHZE',
                'posologie_alternative' => 'Comprimés combinés à doses fixes selon le poids',
                'remarques' => 'DOTS (Directly Observed Treatment) recommandé. Surveillance mensuelle des crachats. Surveiller fonction hépatique (hépatite médicamenteuse).',
                'uuid' => (string) Str::uuid(), 'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'maladie_id' => $maladieIds['Tuberculose multirésistante'] ?? $maladieIds['Tuberculose'] ?? 1,
                'titre' => 'Traitement de la TB multirésistante (MDR-TB)',
                'signes' => 'Même signes que TB ordinaire mais résistance aux antituberculeux de 1ère ligne',
                'diagnostics' => 'Antibiogramme: résistance à rifampicine ± isoniazide, GeneXpert MTB/RIF',
                'germes_nourrisson' => 'Mycobacterium tuberculosis multirésistant',
                'germes_adulte' => 'Mycobacterium tuberculosis multirésistant',
                'traitement_principal' => 'Schéma BPaL: Bédaquiline + Prétomanide + Linézolide + Moxifloxacine ou Clofazimine',
                'posologie_principale' => 'Bédaquiline 200mg 1x/jour pendant 8 mois; Prétomanide 200mg/jour; Linézolide 600mg/jour; pendant 6-9 mois minimum',
                'traitement_alternatif' => 'Schéma raccourci 9-12 mois (si pas de résistance aux fluoroquinolones)',
                'posologie_alternative' => 'Kanamycine ou Amikacine + Fluoroquinolone + Éthionamide + Cyclosérine + Pas',
                'remarques' => 'Traitement long (18-24 mois), coûteux, effets indésirables nombreux (neuropathies, ototoxicité, hépatite).',
                'uuid' => (string) Str::uuid(), 'created_at' => now(),
                'updated_at' => now()
            ],
            
            // ==================== LÈPRE ====================
            [
                'maladie_id' => $maladieIds['Lèpre'] ?? 1,
                'titre' => 'Traitement de la lèpre multibacillaire (MB)',
                'signes' => 'Plaques hypopigmentées avec perte de sensibilité, nodules, épaississement des nerfs périphériques, bacilles acido-alcoolo-résistants (BAAR +)',
                'diagnostics' => 'Examen clinique, bacilloscopie (frottis cutané), test de Ridley',
                'germes_nourrisson' => 'Mycobacterium leprae',
                'germes_adulte' => 'Mycobacterium leprae',
                'traitement_principal' => 'Rifampicine + Dapsone + Clofazimine (schéma OMS 12 mois)',
                'posologie_principale' => 'Rifampicine 600mg 1x/mois supervisé + Dapsone 100mg/jour + Clofazimine 300mg/mois + 50mg/jour pendant 12 mois',
                'traitement_alternatif' => 'Ofloxacine + Rifampicine + Dapsone (schéma alternatif)',
                'posologie_alternative' => 'Ofloxacine 400mg/jour + Rifampicine 600mg/mois + Dapsone 100mg/jour',
                'remarques' => 'Déclaration obligatoire. Suivi régulier. Prévenir réactions lépreuses (syndrome de reversal, érythème noueux lépreux).',
                'uuid' => (string) Str::uuid(), 'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'maladie_id' => $maladieIds['Lèpre'] ?? 1,
                'titre' => 'Traitement de la lèpre paucibacillaire (PB)',
                'signes' => '1-2 lésions cutanées hypopigmentées avec perte de sensibilité, bacilloscopie négative',
                'diagnostics' => 'Examen clinique, bacilloscopie négative, test de Ridley',
                'germes_nourrisson' => 'Mycobacterium leprae',
                'germes_adulte' => 'Mycobacterium leprae',
                'traitement_principal' => 'Rifampicine + Dapsone (schéma OMS 6 mois)',
                'posologie_principale' => 'Rifampicine 600mg 1x/mois supervisé + Dapsone 100mg/jour pendant 6 mois',
                'traitement_alternatif' => 'Ofloxacine + Rifampicine + Dapsone',
                'posologie_alternative' => 'Ofloxacine 400mg/jour + Rifampicine 600mg/mois + Dapsone 100mg/jour pendant 6 mois',
                'remarques' => 'Schéma plus court que MB. Surveiller réactions immunitaires.',
                'uuid' => (string) Str::uuid(), 'created_at' => now(),
                'updated_at' => now()
            ],
            
            // ==================== MALADIES FONGIQUES ====================
            [
                'maladie_id' => $maladieIds['Candidose oropharyngée'] ?? $maladieIds['Candidose systémique'] ?? 1,
                'titre' => 'Traitement de la candidose oropharyngée (muguet)',
                'signes' => 'Enduit blanc crémeux sur la langue et muqueuses buccales, brûlures, dysphagie',
                'diagnostics' => 'Examen clinique, examen direct (pseudomycéliums), culture',
                'germes_nourrisson' => 'Candida albicans',
                'germes_adulte' => 'Candida albicans',
                'traitement_principal' => 'Nystatine suspension buvable',
                'posologie_principale' => 'Nystatine 1ml de suspension 100 000 UI 4x/jour, garder en bouche 1 min puis avaler, pendant 7-10 jours',
                'traitement_alternatif' => 'Miconazole gel buccal ou Fluconazole',
                'posologie_alternative' => 'Miconazole gel 2,5ml 4x/jour; Fluconazole 100mg 1x/jour pendant 7-14 jours si candidose sévère',
                'remarques' => 'Chez le nourrisson: nystatine 1ml 4x/jour. Traiter aussi le sein de la mère si allaitement.',
                'uuid' => (string) Str::uuid(), 'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'maladie_id' => $maladieIds['Candidose systémique'] ?? $maladieIds['Candidose'] ?? 1,
                'titre' => 'Traitement de la candidose systémique / invasif',
                'signes' => 'Fièvre non répondante aux antibiotiques, neutropénie, candidémie, atteinte disséminée',
                'diagnostics' => 'Hémocultures répétées, antigène mannane, imagerie (échographie cardiaque, fundus)',
                'germes_nourrisson' => 'Candida albicans, Candida glabrata, Candida tropicalis',
                'germes_adulte' => 'Candida albicans, C. glabrata, C. krusei, C. tropicalis',
                'traitement_principal' => 'Caspofungine ou Fluconazole (selon espèce et sévérité)',
                'posologie_principale' => 'Caspofengine: 70mg J1 puis 50mg/jour IV; Fluconazole: 800mg J1 puis 400mg/jour IV/PO',
                'traitement_alternatif' => 'Amphotéricine B liposomale',
                'posologie_alternative' => 'Amphotéricine B liposomale 3-5mg/kg/jour IV',
                'remarques' => 'Retirer les cathéters veineux centraux si candidémie. Échographie cardiaque (endocardite). Surveillance ophtalmologique.',
                'uuid' => (string) Str::uuid(), 'created_at' => now(),
                'updated_at' => now()
            ],
            
            // ==================== PARASITOSES ====================
            [
                'maladie_id' => $maladieIds['Ascaridiose'] ?? $maladieIds['Helminthiases'] ?? 1,
                'titre' => 'Traitement des infections à nématodes intestinaux (Ascaris, Ancylostoma, Trichocéphale)',
                'signes' => 'Douleurs abdominales, diarrhée, amaigrissement, anémie (vers), toux si migration larvaire',
                'diagnostics' => 'Examen parasitologique des selles (œufs, larves)',
                'germes_nourrisson' => 'Ascaris lumbricoides, Ancylostoma duodenale, Necator americanus, Trichuris trichiura',
                'germes_adulte' => 'Ascaris lumbricoides, Ancylostoma duodenale, Necator americanus, Trichuris trichiura',
                'traitement_principal' => 'Albendazole',
                'posologie_principale' => 'Albendazole 400mg dose unique (Adultes et enfants > 2 ans); Enfants 1-2 ans: 200mg dose unique',
                'traitement_alternatif' => 'Mébendazole ou Pyrantel',
                'posologie_alternative' => 'Mébendazole 500mg dose unique ou 100mg 2x/jour pendant 3 jours; Pyrantel 11mg/kg dose unique',
                'remarques' => 'Deworming de masse recommandé en zone endémique (1-2 fois/an). Prise pendant les repas.',
                'uuid' => (string) Str::uuid(), 'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'maladie_id' => $maladieIds['Schistosomiase'] ?? $maladieIds['Bilharziose'] ?? 1,
                'titre' => 'Traitement de la schistosomiase (bilharziose)',
                'signes' => 'Dermatite prurigineuse lors de la pénétration des cercaires (tanapox), puis fièvre, myalgies, puis manifestation chroniques: hématurie (S. haematobium), hepatosplénomégalie, cirrhose (S. mansoni, S. japonicum)',
                'diagnostics' => 'Recherche d\'œufs dans les urines (S. haematobium) ou les selles (S. mansoni), sérologie',
                'germes_nourrisson' => 'Schistosoma haematobium, S. mansoni, S. japonicum, S. intercalatum',
                'germes_adulte' => 'Schistosoma haematobium, S. mansoni, S. japonicum',
                'traitement_principal' => 'Praziquantel',
                'posologie_principale' => 'Praziquantel 40mg/kg en dose unique (S. mansoni, S. haematobium); 60mg/kg en dose unique (S. japonicum, S. intercalatum)',
                'traitement_alternatif' => 'Oxamniquine (S. mansoni uniquement)',
                'posologie_alternative' => 'Oxamniquine 15mg/kg (dose unique) ou 10mg/kg x2 à 3 jours',
                'remarques' => 'Traitement de masse en zone endémique: Praziquantel 40mg/kg 1-2x/an. Ne pas traiter pendant le premier trimestre de grossesse (sauf si nécessaire).',
                'uuid' => (string) Str::uuid(), 'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'maladie_id' => $maladieIds['Filariose lymphatique'] ?? 1,
                'titre' => 'Traitement de la filariose lymphatique (Wuchereria bancrofti, Brugia malayi)',
                'signes' => 'Lymphœdème des membres inférieurs, hydrocèle, éléphantiasis, lymphangite récurrente, fièvres filariennes',
                'diagnostics' => 'Microscopie (microfilaires dans le sang nocturne), test antigénique rapide, sérologie, échographie testiculaire',
                'germes_nourrisson' => 'Wuchereria bancrofti, Brugia malayi',
                'germes_adulte' => 'Wuchereria bancrofti, Brugia malayi',
                'traitement_principal' => 'Diéthylcarbamazine (DEC) + Albendazole (treatment de masse)',
                'posologie_principale' => 'DEC 6mg/kg/jour + Albendazole 400mg en dose unique, 1x/an pendant 5 ans minimum',
                'traitement_alternatif' => 'Ivermectine + Albendazole',
                'posologie_alternative' => 'Ivermectine 200µg/kg + Albendazole 400mg en dose unique annuelle',
                'remarques' => 'Programme d\'élimination MDA (Mass Drug Administration) en zone endémique. Chirurgie lymphœdème.',
                'uuid' => (string) Str::uuid(), 'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'maladie_id' => $maladieIds['Onchocercose'] ?? 1,
                'titre' => 'Traitement de l\'onchocercose (cécité des rivières)',
                'signes' => 'Prurit cutané, dermatite papuleuse, nodules sous-cutanés, troubles visuels progressifs, cécité',
                'diagnostics' => 'Examen ophtalmologique (kératite ponctuée, atrophie optique), skin snips (microfilaires), PCR, sérologie',
                'germes_nourrisson' => 'Onchocerca volvulus',
                'germes_adulte' => 'Onchocerca volvulus',
                'traitement_principal' => 'Ivermectine (Mectizan®)',
                'posologie_principale' => 'Ivermectine 150µg/kg en dose unique orale, à répéter tous les 6 ou 12 mois',
                'traitement_alternatif' => 'Doxycycline 200mg/jour pendant 4-6 semaines (action anti-Wolbachia)',
                'posologie_alternative' => 'Doxycycline: 200mg/jour pendant 4-6 semaines en association avec ivermectine',
                'remarques' => 'Contrôle vectoriel (mouches simulies). Programme APOC (African Programme for Onchocerciasis Control). Surveiller réaction de Mazzotti (effets indésirables après traitement).',
                'uuid' => (string) Str::uuid(), 'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'maladie_id' => $maladieIds['Leishmaniose viscérale'] ?? 1,
                'titre' => 'Traitement de la leishmaniose viscérale (Kala-azar)',
                'signes' => 'Fièvre prolongée, splénomégalie, hépatomégalie, pancytopénie, amaigrissement, mélanodermie',
                'diagnostics' => 'Examen parasitologique (ponction splénique/ganglionnaire), sérologie (rK39), PCR',
                'germes_nourrisson' => 'Leishmania donovani, L. infantum',
                'germes_adulte' => 'Leishmania donovani, L. infantum',
                'traitement_principal' => 'Amphotéricine B liposomale (L-AmB)',
                'posologie_principale' => 'L-AmB 10mg/kg/jour IV pendant 5 jours puis 10mg/kg J10, J14, J21 (dose totale 18-21mg/kg)',
                'traitement_alternatif' => 'Méglumine antimoniate (Glucantime) ou Miltefosine',
                'posologie_alternative' => 'Méglumine antimoniate 20mg Sb/kg/jour IM/IV pendant 28 jours; Miltefosine 2,5mg/kg/jour PO pendant 28 jours',
                'remarques' => 'PKDL (dermatite post-kala-azar) peut apparaître après guérison. Surveiller fonction cardiaque (antimoniatés).',
                'uuid' => (string) Str::uuid(), 'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'maladie_id' => $maladieIds['Gale'] ?? 1,
                'titre' => 'Traitement de la gale (Sarcoptes scabiei)',
                'signes' => 'Prurit intense nocturne, sillons interdigitaux, nodules axillaires, lésions de grattage',
                'diagnostics' => 'Examen clinique, examen microscopique (acariens, œufs, déjections)',
                'germes_nourrisson' => 'Sarcoptes scabiei var. hominis',
                'germes_adulte' => 'Sarcoptes scabiei',
                'traitement_principal' => 'Perméthrine crème 5%',
                'posologie_principale' => 'Perméthrine 5%: appliquer du cou vers les pieds, laisser 8-12h puis laver. Répéter à 7 jours.',
                'traitement_alternatif' => 'Benzoate de benzyle ou Ivermectine orale',
                'posologie_alternative' => 'Benzoate de benzyle 25%: appliquer 3 nuits consécutives; Ivermectine 200µg/kg dose unique per os (répéter à 7 jours)',
                'remarques' => 'Traiter tous les membres du foyer. Lavage des draps et vêtements à 60°C. Perméthrine de préférence chez le nourrisson.',
                'uuid' => (string) Str::uuid(), 'created_at' => now(),
                'updated_at' => now()
            ],
            
            // ==================== INFECTIONS URINAIRES ====================
            [
                'maladie_id' => $maladieIds['Cystite'] ?? $maladieIds['Infection urinaire'] ?? 1,
                'titre' => 'Traitement de la cystite aiguë non compliquée (femme)',
                'signes' => 'Dysurie, pollakiurie, urines troubles ou sanglantes, douleurs sus-pubiennes',
                'diagnostics' => 'ECBU: leucocyturie, bactériurie > 10³ UFC/ml, bandelette urinaire',
                'germes_nourrisson' => null,
                'germes_adulte' => 'Escherichia coli (80-85%), Proteus mirabilis, Klebsiella pneumoniae, Enterococcus',
                'traitement_principal' => 'Nitrofurantoïne ou Phosphate fosfomycine',
                'posologie_principale' => 'Nitrofurantoïne 100mg 2x/jour pendant 5 jours; Fosfomycine 3g dose unique',
                'traitement_alternatif' => 'Ciprofloxacine ou Co-trimoxazole (si germes sensibles)',
                'posologie_alternative' => 'Ciprofloxacine 250mg 2x/jour pendant 3 jours; Co-trimoxazole 800/160mg 2x/jour pendant 3 jours',
                'remarques' => 'Éviter les fluoroquinolones en 1ère intention (résistance). Femme enceinte: amoxicilline ou nitrofurantoïne.',
                'uuid' => (string) Str::uuid(), 'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'maladie_id' => $maladieIds['Pyélonéphrite'] ?? $maladieIds['Infection urinaire'] ?? 1,
                'titre' => 'Traitement de la pyélonéphrite aiguë',
                'signes' => 'Fièvre > 38,5°C, douleurs lombaires, vomissements, signes cystitaires, syndrome inflammatoire biologique',
                'diagnostics' => 'ECBU positive (leucocyturie + bactériurie), hémocultures si fièvre élevée, échographie si doute',
                'germes_nourrisson' => null,
                'germes_adulte' => 'Escherichia coli, Proteus, Klebsiella, Enterococcus, Pseudomonas',
                'traitement_principal' => 'Ceftriaxone IV puis relais oral',
                'posologie_principale' => 'Ceftriaxone 1g/jour IV pendant 3-5 jours puis relais par ciprofloxacine 500mg 2x/jour pour compléter 10-14 jours',
                'traitement_alternatif' => 'Ciprofloxacine alone (si germes sensibles)',
                'posologie_alternative' => 'Ciprofloxacine 500mg 2x/jour PO pendant 7-10 jours',
                'remarques' => 'Hospitalisation si vomissements, sepsis, obstruction, femme enceinte. Bilan urologique si pyélonéphrites récidivantes.',
                'uuid' => (string) Str::uuid(), 'created_at' => now(),
                'updated_at' => now()
            ],
            
            // ==================== SYPHILIS / IST ====================
            [
                'maladie_id' => $maladieIds['Syphilis'] ?? 1,
                'titre' => 'Traitement de la syphilis précoce (primaire, secondaire, latente précoce)',
                'signes' => 'Syphilis primaire: chancre indolore; Syphilis secondaire: rash, syphilides, condylomes plats; Latente: asymptomatique',
                'diagnostics' => 'Sérologie VDRL/RPR + TPHA/TPPA, examen direct si chancre',
                'germes_nourrisson' => null,
                'germes_adulte' => 'Treponema pallidum',
                'traitement_principal' => 'Pénicilline G benzathine',
                'posologie_principale' => 'Syphilis précoce: Benzathine benzylpénicilline 2,4 MUI IM dose unique (2 injections 1,2 MUI de chaque côté); Syphilis tardive: même dose x3 à intervalles de 1 semaine',
                'traitement_alternatif' => 'Doxycycline (si allergie pénicilline)',
                'posologie_alternative' => 'Doxycycline 100mg 2x/jour pendant 14 jours (précoce) ou 28 jours (tardive)',
                'remarques' => 'Déclaration obligatoire. Recherche et traitement du/des partenaire(s). Réaction de Jarisch-Herxheimer possible (fièvre, frissons).',
                'uuid' => (string) Str::uuid(), 'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'maladie_id' => $maladieIds['Gonococcie'] ?? 1,
                'titre' => 'Traitement de la gonococcie (blennorragie)',
                'signes' => 'Urétrite purulente (homme), cervicite mucopurulente (femme), doulent pelviennes, écoulement vaginal/pénien',
                'diagnostics' => 'Examen direct (diplocoques Gram-), culture, PCR (test deattie), antibiogramme',
                'germes_nourrisson' => null,
                'germes_adulte' => 'Neisseria gonorrhoeae',
                'traitement_principal' => 'Ceftriaxone IM/IV + Azithromycine PO',
                'posologie_principale' => 'Ceftriaxone 500mg IM dose unique + Azithromycine 1g PO dose unique (traite aussi Chlamydia co-infection)',
                'traitement_alternatif' => 'Cefixime + Azithromycine',
                'posologie_alternative' => 'Cefixime 400mg PO dose unique + Azithromycine 1g PO dose unique',
                'remarques' => 'Resistance croissante aux fluoroquinolones et céphalosporines orales. Test de vérification de la guérison (TVG) recommandé. Dépistage VIH.',
                'uuid' => (string) Str::uuid(), 'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'maladie_id' => $maladieIds['Chlamydia'] ?? 1,
                'titre' => 'Traitement des infections à Chlamydia trachomatis',
                'signes' => 'Urétrite, cervicite, saignements intermenstruels, doulent pelviennes, conjonctivite à inclusions',
                'diagnostics' => 'PCR urinaire/génital, culture (rare), sérologie (serretum)',
                'germes_nourrisson' => null,
                'germes_adulte' => 'Chlamydia trachomatis D-K (IST), L1-L3 (trachome)',
                'traitement_principal' => 'Azithromycine ou Doxycycline',
                'posologie_principale' => 'Azithromycine 1g PO dose unique; Doxycycline 100mg 2x/jour pendant 7 jours (préféré)',
                'traitement_alternatif' => 'Lévofloxacine',
                'posologie_alternative' => 'Lévofloxacine 500mg 1x/jour pendant 7 jours',
                'remarques' => 'Traiter aussi le partenaire. Tests de contrôle si infection ano-rectale ou si symptômes persistent.',
                'uuid' => (string) Str::uuid(), 'created_at' => now(),
                'updated_at' => now()
            ],
            
            // ==================== ÉTAT DE MAL CONVULSIF ====================
            [
                'maladie_id' => $maladieIds['État de mal convulsif'] ?? 1,
                'titre' => 'Traitement de l\'état de mal convulsif',
                'signes' => 'Crises convulsives continues ou répétées sans reprise de conscience, risque d\'acidose, rhabdomyolyse, insuffisance respiratoire',
                'diagnostics' => 'EEG si disponible, monitorage cardio-respiratoire, bilan (glycémie, électrolytes, CPK, lactates)',
                'germes_nourrisson' => null,
                'germes_adulte' => null,
                'traitement_principal' => 'Diazépam IV + Phénytoïne ou Fosphénytoïne',
                'posologie_principale' => 'Diazépam 10mg IV lentement (5mg/min) toutes les 5-10min jusqu\'à 30mg max; puis Phénytoïne 15-20mg/kg IV dose de charge puis 5mg/kg/jour entretien',
                'traitement_alternatif' => 'Lorazépam IV ou Midazolam IM/IN ou Phénobarbital',
                'posologie_alternative' => 'Lorazépam 0,1mg/kg IV; Midazolam 10mg IM/IN; Phénobarbital 20mg/kg IV',
                'remarques' => 'Libération des voies aériennes (canule de Guedel), oxygénation, surveillance cardio-respiratoire. Traitement de la cause sous-jacente (hypoglycémie, méningite, éclampsie).',
                'uuid' => (string) Str::uuid(), 'created_at' => now(),
                'updated_at' => now()
            ],
            
            // ==================== INTOXICATIONS ====================
            [
                'maladie_id' => $maladieIds['Intoxication au paracétamol'] ?? 1,
                'titre' => 'Traitement de l\'intoxication au paracétamol',
                'signes' => 'Phase 1 (0-24h): nausées, vomissements, pâleur; Phase 2 (24-72h): douleur abdominale, cytolyse hépatique; Phase 3 (72-96h): insuffisance hépatique fulminante',
                'diagnostics' => 'Taux de paracétamol plasmatique > 150mg/L à H4 ou > courbe de toxicité de Rumack; PT/INR élevé, cytolyse',
                'germes_nourrisson' => null,
                'germes_adulte' => null,
                'traitement_principal' => 'N-Acétylcystéine (NAC) IV (Antidote)',
                'posologie_principale' => 'NAC 150mg/kg en 1h IV, puis 50mg/kg en 4h, puis 100mg/kg en 16h (protocole 20h) jusqu\'à toxicité écartée',
                'traitement_alternatif' => 'N-Acétylcystéine orale (moins utilisé)',
                'posologie_alternative' => 'NAC per os: 140mg/kg dose de charge puis 70mg/kg toutes les 4h pendant 72h',
                'remarques' => 'Efficacité maximale si NAC administré < 8h après ingestion. Indication absolue si paracétamol > 150mg/L à H4 ou > 75mg/L à H8. Traitement préventif si ingestion > 10g ou > 150mg/kg.',
                'uuid' => (string) Str::uuid(), 'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'maladie_id' => $maladieIds['Intoxication aux organophosphorés'] ?? 1,
                'titre' => 'Traitement de l\'intoxication aux insecticides organophosphorés (cholinestérases)',
                'signes' => 'SLUDGE syndrome (Salivation, Lacrimation, Urination, Defecation, GI distress, Emesis), myosis, bradycardie, bronchospasme, fasciculations, paralysie musculaire, coma',
                'diagnostics' => 'Histoire d\'exposition, signes cliniques cholinergiques, taux de cholinestérase érythrocytaire < 30% (confirmatoire)',
                'germes_nourrisson' => null,
                'germes_adulte' => null,
                'traitement_principal' => 'Atropine + Pralidoxime',
                'posologie_principale' => 'Atropine 2-5mg IV toutes les 5-15min jusqu\'à désécherage (disparition des sécrétions); Pralidoxime 1-2g IV en 30min puis 500mg/h perfusion continue (ou 30mg/kg/4h)',
                'traitement_alternatif' => 'Oxime + Atropine (traitement d\'entretien prolongé)',
                'posologie_alternative' => 'Pralidoxime 1g IV toutes les 6h pendant 24-48h',
                'remarques' => 'Décontamination (gants,距离). Assistance respiratoire (risque de paralysie respiratoire). Surveillance cardiaque. Lavage gastrique si ingestion récente.',
                'uuid' => (string) Str::uuid(), 'created_at' => now(),
                'updated_at' => now()
            ],
        ];
        
        DB::table('protocole_traitements')->insert($protocoles);
    }
}